# This is a Makefile fragment, see ../Makefile

INC += pv/endpoint.h
INC += pv/endpointProvider.h
INC += pv/singleServiceEndpoint.h

SRC_DIRS += $(PVLOCAL_SRC)/endpoint

LIBSRCS += endpointProvider.cpp

