# This is a Makefile fragment, see ../Makefile

SRC_DIRS += $(PVLOCAL_SRC)/pvAccess

INC += pv/channelProviderLocal.h
INC += pv/pvaServer.h

DBD += registerChannelProviderLocal.dbd

LIBSRCS += channelProviderLocal.cpp
LIBSRCS += registerChannelProviderLocal.cpp
LIBSRCS += pvaServer.cpp
